# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ca21d1e2bf26142f335dc176b6b8062c414442dc1d82c5cbaabd3b816d37febbfffbc540e7e15ddb8e4d741e93a8526d010376decebf89de3a54499056a7b9b

test:
  secret_key_base: a539f2ccf713ba3c6aade82fd8c8994d7642b415411ba51ef8211deaa30bc1cc4844890bb0591fa1072ff56e36f471826a3d9b4d7161e2965df75d7ddf7be28d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
